In [7]:
import numpy as np

n1=np.array([[1,2,3,4],[5,6,7,8]])
n1T=n1.transpose()
n2=np.resize(n1, (4,2))
n2T=n2.transpose()
print(f"n1 is row-major, shape={n1.shape},\n n1:{n1}\nn1T is column-major but shape changed.n1T={n1T}")
print("-"*20)
print(f"n2 is row-major, shape={n2.shape},\n n1:{n2}\nn2T is column-major but shape changedn2T={n2T}")
print(f"\n{'*'*20}\n so, n2T is the same shape with n1, from row-major to column-major")

n1 is row-major, shape=(2, 4),
 n1:[[1 2 3 4]
 [5 6 7 8]]
n1T is column-major but shape changed.n1T=[[1 5]
 [2 6]
 [3 7]
 [4 8]]
--------------------
n2 is row-major, shape=(4, 2),
 n1:[[1 2]
 [3 4]
 [5 6]
 [7 8]]
n2T is column-major but shape changedn2T=[[1 3 5 7]
 [2 4 6 8]]

********************
 so, n2T is the same shape with n1, from row-major to column-major


In [8]:
print(n1.transpose())

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [ ]:
import matplotlib.pyplot as plt

plt.plot(n1[0,:], label='L')
plt.plot(n1T[:,1],label='T')
plt.legend()
plt.show()